# Generated by Django 5.1.7 on 2025-04-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0019_merge_20250414_1423'),
        ('medarbetarapp', '0020_merge_20250415_0740'),
    ]

    operations = [
    ]
