# Generated by Django 5.1.7 on 2025-04-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0022_survey_published_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='yes_no_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
