# Generated by Django 5.1.7 on 2025-04-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medarbetarapp', '0021_merge_20250416_1319'),
        ('medarbetarapp', '0022_survey_published_count'),
    ]

    operations = [
    ]
